easy_admin:
    site_name: Gite de la calquière | <strong>Bonjour père</strong>
    user:
        display_name: false
    entities:
       Booking:
            class: App\Entity\Booking
            list:
                fields: ['customer', 'start', 'end']

       Contact:
         class: App\Entity\Contact
         list:
           fields: ['Name', 'email', 'status', 'date']

       Price:
            class: App\Entity\Price
            list:
              fields: ['title']
            form:
                fields:
                      - { property: 'title' }
                      - { property: 'titlePrice' }
                      - { property: 'content', css_class: 'awesome-ckeditor', type: 'textarea' }
    list:
        item_permission: 'ROLE_ADMIN'
    design:
        brand_color: '#1ABC9C'
        menu:
            - { entity: 'Booking', icon: 'book'}
            - { entity: 'Price', icon: 'dollar-sign'}
            - { entity: 'Contact', icon: 'address-book'}
            - { label: 'acceuil', route: home, icon: 'home'}
            - { label: 'chart', route: chart, icon: 'home'}
        assets:
            js:
#              -  '//cdn.quilljs.com/1.3.6/quill.min.js'
              -  'https://cdnjs.cloudflare.com/ajax/libs/froala-editor/3.0.6/js/froala_editor.min.js'
              -  'build/wisiwyg.js'


            css:
#              -  '//cdn.quilljs.com/1.3.6/quill.snow.css'
#              -  '//cdn.quilljs.com/1.3.6/quill.bubble.css'
               - 'https://cdnjs.cloudflare.com/ajax/libs/froala-editor/3.0.6/css/froala_editor.min.css'
